name: aria
channels:
  - 1adrianb
  - conda-forge
dependencies:
  - aom=3.9.1
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.15.2
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - contourpy=1.3.1
  - cpython=3.11.11
  - cycler=0.12.1
  - dataclasses=0.8
  - dav1d=1.2.1
  - dbus=1.13.6
  - expat=2.6.4
  - face_alignment=1.4.1
  - ffmpeg=7.1.0
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2025.3.0
  - gdk-pixbuf=2.42.12
  - geos=3.13.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=10.3.0
  - hdf5=1.14.3
  - hickle=5.0.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.12.30
  - imageio=2.37.0
  - imath=3.1.12
  - imgaug=0.4.0
  - importlib-metadata=8.6.1
  - iopath=0.1.10
  - jasper=4.2.4
  - jinja2=3.1.6
  - joblib=1.4.2
  - jxrlib=1.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.23.1
  - libass=0.17.3
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libcxx=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgettextpo=0.23.1
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libhwloc=2.11.2
  - libhwy=1.1.0
  - libiconv=1.18
  - libintl=0.23.1
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopencv=4.11.0
  - libopenvino=2025.0.0
  - libopenvino-arm-cpu-plugin=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.3.1
  - libpng=1.6.47
  - libprotobuf=5.28.3
  - librsvg=2.58.4
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libusb=1.0.27
  - libuv=1.50.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.6
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lightning=2.5.0.post0
  - lightning-utilities=0.14.0
  - llvm-openmp=19.1.7
  - llvmlite=0.43.0
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.4
  - nomkl=1.0
  - numba=0.60.0
  - opencv=4.11.0
  - openexr=3.3.2
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openssl=3.4.1
  - optree=0.14.1
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.1
  - pcre2=10.44
  - pip=25.0.1
  - pixman=0.44.2
  - portalocker=3.0.0
  - pthread-stubs=0.4
  - pugixml=1.15
  - py-opencv=4.11.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.11
  - pytorch=2.6.0
  - pytorch-lightning=2.5.0.post0
  - pytz=2024.1
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - qhull=2020.2
  - rav1e=0.6.6
  - readline=8.2
  - requests=2.32.3
  - scikit-image=0.25.0
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sdl2=2.32.50
  - sdl3=3.2.4
  - setuptools=75.8.0
  - shapely=2.0.7
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - svt-av1=2.3.0
  - tbb=2022.0.0
  - threadpoolctl=3.5.0
  - tifffile=2025.2.18
  - tk=8.6.13
  - torchmetrics=1.6.2
  - torchvision=0.21.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib-ng=2.2.4
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.1.0
      - chumpy==0.70
      - click==8.1.8
      - compress-pickle==2.1.0
      - docker-pycreds==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - munch==4.0.0
      - numpy==1.26.4
      - omegaconf==2.3.0
      - pillow==10.2.0
      - platformdirs==4.3.6
      - projectaria-client-sdk==1.1.0
      - projectaria-tools==1.5.2a1
      - protobuf==5.29.3
      - psutil==7.0.0
      - pyarrow==19.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - rerun-sdk==0.22.0
      - scikit-video==1.1.11
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - smmap==5.0.2
      - soundfile==0.13.1
      - sympy==1.13.1
      - termcolor==2.5.0
      - torch==2.2.2
      - torchaudio==2.6.0
      - wandb==0.19.8
